#  █████╗ ███╗   ██╗██╗███╗   ███╗ █████╗ ████████╗██╗ ██████╗ ███╗   ██╗
# ██╔══██╗████╗  ██║██║████╗ ████║██╔══██╗╚══██╔══╝██║██╔═══██╗████╗  ██║
# ███████║██╔██╗ ██║██║██╔████╔██║███████║   ██║   ██║██║   ██║██╔██╗ ██║
# ██╔══██║██║╚██╗██║██║██║╚██╔╝██║██╔══██║   ██║   ██║██║   ██║██║╚██╗██║
# ██║  ██║██║ ╚████║██║██║ ╚═╝ ██║██║  ██║   ██║   ██║╚██████╔╝██║ ╚████║
# ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝╚═╝     ╚═╝╚═╝  ╚═╝   ╚═╝   ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
#------------------------------------------------------------------------



animations {
    enabled = yes

    bezier = ease, 0.25, 0.1, 0.25, 1.0
    bezier = snappy, 0.2, 0.9, 0.25, 1.0

    animation = windows, 1, 3, snappy, gnomed
    animation = windowsOut, 1, 3, snappy, slide bottom
    animation = windowsMove, 1, 2, snappy, slide

    animation = layers, 1, 3, snappy, popin
    animation = fade, 1, 2, snappy
    animation = border, 1, 1, snappy
    animation = workspaces, 1, 3, snappy, fade
    animation = specialWorkspaceIn, 1, 3, snappy, slide top
    animation = specialWorkspaceOut, 1, 2, snappy, slide bottom
} 
