# ███╗   ███╗██╗███████╗ ██████╗
# ████╗ ████║██║██╔════╝██╔════╝
# ██╔████╔██║██║███████╗██║     
# ██║╚██╔╝██║██║╚════██║██║     
# ██║ ╚═╝ ██║██║███████║╚██████╗
# ╚═╝     ╚═╝╚═╝╚══════╝ ╚═════╝
#-------------------------------



misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    disable_splash_rendering = true
    initial_workspace_tracking = 1
    key_press_enables_dpms = true  # key press wakes display
    mouse_move_enables_dpms = true # mouse move wakes display
}

bindl = ,switch:on:Lid Switch,exec,~/.config/hypr/scripts/lid.sh close
bindl = ,switch:off:Lid Switch,exec,~/.config/hypr/scripts/lid.sh open

binds {
    hide_special_on_workspace_change = true # Drop-down console retracts when switching workspace
}
